<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/TallyPrimeConnector.Contracts/TallyPrimeConnector.Contracts.csproj" /><ProjectReference Include="../../src/TallyPrimeConnector.Core/TallyPrimeConnector.Core.csproj" /><ProjectReference Include="../../src/TallyPrimeConnector.Tally/TallyPrimeConnector.Tally.csproj" /><ProjectReference Include="../../src/TallyPrimeConnector.Processing/TallyPrimeConnector.Processing.csproj" /></ItemGroup></Project>
